/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sejmngram extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 545260119;

	/**
	 * The singleton instance of <code>sejmngram</code>
	 */
	public static final Sejmngram SEJMNGRAM = new Sejmngram();

	/**
	 * No further instances allowed
	 */
	private Sejmngram() {
		super("sejmngram");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.jooq.util.maven.example.tables.Ngrams.NGRAMS);
	}
}
