/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in sejmngram
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table sejmngram.ngrams
	 */
	public static final org.jooq.util.maven.example.tables.Ngrams NGRAMS = org.jooq.util.maven.example.tables.Ngrams.NGRAMS;
}
