#!/usr/bin/python
# -*- coding: utf-8 -*-

POSITION_PREFIXES = [
        'Marszałek Senior',
        'Wicemarszałek',
        'Poseł Sekretarz',
        'Marszałek',
        'Prezydent Rzeczypospolitej Polskiej',
        'Poseł',
        'Minister Edukacji Narodowej',
        'Minister Zdrowia',
        'Minister Finansów',
        'Główny Inspektor Sanitarny',
        'Przedstawiciel Komitetu Inicjatywy Ustawodawczej',
        'Minister Spraw Zagranicznych',
        'Minister Środowiska',
        'Prezes Rady Ministrów',
        'Rzecznik Praw Obywatelskich',
        'Minister Skarbu Państwa',
        'Podsekretarz Stanu w Ministerstwie Finansów',
        'Sekretarz Stanu w Ministerstwie Pracy i Polityki Społecznej',
        'Podsekretarz Stanu w Ministerstwie Spraw Wewnętrznych',
        'Podsekretarz Stanu w Ministerstwie Skarbu Państwa',
        'Podsekretarz Stanu w Ministerstwie Edukacji Narodowej',
        'Sekretarz Stanu w Ministerstwie Finansów',
        'Podsekretarz Stanu w Ministerstwie Rolnictwa i Rozwoju Wsi',
        'Podsekretarz Stanu w Ministerstwie Spraw Zagranicznych',
        'Sekretarz Stanu w Ministerstwie Skarbu Państwa',
        'Sekretarz Stanu w Kancelarii Prezydenta RP',
        'Podsekretarz Stanu w Ministerstwie Pracy i Polityki Społecznej',
        'Minister Pracy i Polityki Społecznej',
        'Sekretarz Stanu w Ministerstwie Zdrowia',
        'Podsekretarz Stanu w Ministerstwie Transportu, Budownictwa i Gospodarki Morskiej',
        'Sekretarz Stanu w Ministerstwie Obrony Narodowej',
        'Podsekretarz Stanu w Ministerstwie Gospodarki',
        'Wiceprezes Rady Ministrów Minister Gospodarki',
        'Sekretarz Stanu w Ministerstwie Gospodarki',
        'Sekretarz Stanu w Ministerstwie Rolnictwa i Rozwoju Wsi',
        'Sekretarz Stanu w Ministerstwie Administracji i Cyfryzacji',
        'Podsekretarz Stanu w Ministerstwie Środowiska',
        'Podsekretarz Stanu w Ministerstwie Nauki i Szkolnictwa Wyższego',
        'Sekretarz Stanu w Ministerstwie Transportu, Budownictwa i Gospodarki Morskiej',
        'Sekretarz Stanu w Ministerstwie Sportu i Turystyki',
        'Sekretarz Stanu w Ministerstwie Spraw Zagranicznych',
        'Minister Kultury i Dziedzictwa Narodowego',
        'Podsekretarz Stanu w Ministerstwie Sprawiedliwości',
        'Sekretarz Stanu w Ministerstwie Spraw Wewnętrznych',
        'Podsekretarz Stanu w Ministerstwie Administracji i Cyfryzacji',
        'Sekretarz Stanu w Ministerstwie Sprawiedliwości',
        'Sekretarz Stanu w Ministerstwie Kultury i Dziedzictwa Narodowego',
        'Podsekretarz Stanu w Ministerstwie Zdrowia'
    ]

MONTHS = {
            "stycznia"      :   1,
            "lutego"        :   2,
            "marca"         :   3,
            "kwietnia"      :   4,
            "maja"          :   5,
            "czerwca"       :   6,
            "lipca"         :   7,
            "sierpnia"      :   8,
            "września"      :   9,
            "października"  :   10,
            "listopada"	    :	11,
            "grudnia"	    :	12,
        }


