/**
 * This class is generated by jOOQ
 */
package org.jooq.util.maven.example.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ngrams extends org.jooq.impl.TableImpl<org.jooq.util.maven.example.tables.records.NgramsRecord> {

	private static final long serialVersionUID = -362593313;

	/**
	 * The singleton instance of <code>sejmngram.ngrams</code>
	 */
	public static final org.jooq.util.maven.example.tables.Ngrams NGRAMS = new org.jooq.util.maven.example.tables.Ngrams();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.jooq.util.maven.example.tables.records.NgramsRecord> getRecordType() {
		return org.jooq.util.maven.example.tables.records.NgramsRecord.class;
	}

	/**
	 * The column <code>sejmngram.ngrams.id</code>.
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.NgramsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sejmngram.ngrams.datefrom</code>.
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.NgramsRecord, java.sql.Timestamp> DATEFROM = createField("datefrom", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>sejmngram.ngrams.dateto</code>.
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.NgramsRecord, java.sql.Timestamp> DATETO = createField("dateto", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>sejmngram.ngrams.ngram</code>.
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.NgramsRecord, java.lang.String> NGRAM = createField("ngram", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>sejmngram.ngrams.nrOccurences</code>.
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.NgramsRecord, java.lang.Integer> NROCCURENCES = createField("nrOccurences", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>sejmngram.ngrams.content</code>.
	 */
	public final org.jooq.TableField<org.jooq.util.maven.example.tables.records.NgramsRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.length(16777215), this, "");

	/**
	 * Create a <code>sejmngram.ngrams</code> table reference
	 */
	public Ngrams() {
		this("ngrams", null);
	}

	/**
	 * Create an aliased <code>sejmngram.ngrams</code> table reference
	 */
	public Ngrams(java.lang.String alias) {
		this(alias, org.jooq.util.maven.example.tables.Ngrams.NGRAMS);
	}

	private Ngrams(java.lang.String alias, org.jooq.Table<org.jooq.util.maven.example.tables.records.NgramsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ngrams(java.lang.String alias, org.jooq.Table<org.jooq.util.maven.example.tables.records.NgramsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.jooq.util.maven.example.Sejmngram.SEJMNGRAM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.jooq.util.maven.example.tables.records.NgramsRecord, java.lang.Integer> getIdentity() {
		return org.jooq.util.maven.example.Keys.IDENTITY_NGRAMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.NgramsRecord> getPrimaryKey() {
		return org.jooq.util.maven.example.Keys.KEY_NGRAMS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.NgramsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.jooq.util.maven.example.tables.records.NgramsRecord>>asList(org.jooq.util.maven.example.Keys.KEY_NGRAMS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.util.maven.example.tables.Ngrams as(java.lang.String alias) {
		return new org.jooq.util.maven.example.tables.Ngrams(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.jooq.util.maven.example.tables.Ngrams rename(java.lang.String name) {
		return new org.jooq.util.maven.example.tables.Ngrams(name, null);
	}
}
